version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000

  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000